platform :ios, "7.0"
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'SVPullToRefresh'
pod 'SDWebImage'
pod 'Surfboard'
pod 'IPDashedLineView'
pod 'RESideMenu'
pod 'jastor'
pod 'TouchJSON'
pod 'LMDropdownView'
pod 'FMDB'
pod 'BTBadgeView'
pod 'SCLAlertView-Objective-C'
pod 'TCBlobDownload'
pod 'ZipArchive', '~> 1.4.0'
pod 'PDKeychainBindingsController', '~> 0.0.1'